core/urls.py
from django.conf.urls import url
from django.urls import include
from .views import Home, change_password
from django.contrib.auth.decorators import login_required

app_name = 'core'

urlpatterns = [
    url(r'^$', login_required(Home.as_view()), name='home'),
    url(r'', include('django.contrib.auth.urls')),
    url(r'^password/$', change_password, name='change_password'),
]

turno/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views
from .views import *

app_name = 'turno'


turno_patterns = ([
                      url(r'^obrasociallistar/', login_required(ObrasocialListar.as_view()), name='obrasocial_list_view'),
                      url(r'^obrasocialcrear/$', login_required(ObrasocialCrear.as_view()), name='obrasocial_crear'),
                      url(r'^obrasocialeliminar/(?P<pk>\d+)/$', login_required(ObrasocialEliminar.as_view()), name='obrasocial_eliminar'),
                      url(r'^obrasocialactualizar/(?P<pk>\d+)/$', login_required(ObrasocialActualizar.as_view()), name='obrasocial_actualizar'),
                      url(r'^medicolistar/', login_required(MedicoListar.as_view()), name='med_listar'),
                      url(r'^medicocrear/$', login_required(MedicoCrear.as_view()), name='med_crear'),
                      url(r'^medicoactualizar/(?P<pk>\d+)/$', login_required(MedicoActualizar.as_view()), name='med_actualizar'),
                      url(r'^medicoeliminar/(?P<pk>\d+)/$', login_required(MedicoEliminar.as_view()), name='med_eliminar'),
                      url(r'^pacientelistar/', login_required(PacienteListar.as_view()), name='pac_listar'),
                      url(r'^pacientecrear/$', login_required(PacienteCrear.as_view()), name='pac_crear'),
                      url(r'^pacienteactualizar/(?P<pk>\d+)/$', login_required(PacienteActualizar.as_view()), name='pac_actualizar'),
                      url(r'^pacienteactualizarcorregir/(?P<pk>\d+)/$', login_required(PacienteCorregirPopUp.as_view()), name='pac_corregir_popup'),
                      url(r'^pacienteeliminar/(?P<pk>\d+)/$', login_required(PacienteEliminar.as_view()), name='pac_eliminar'),
                      url(r'^pacientecorregir/', login_required(PacienteCorregir.as_view()), name='pac_corregir'),
                      url(r'^pacientemarcarcorregido/', marcar_paciente_corregido, name='pac_marcar_corregido'),
                      path('ajax/carga_provincias/', carga_provincias, name='correr_prov'),
                      path('ajax/carga_departamentos/', carga_departamentos, name='correr_dpto'),
                      path('ajax/carga_localidades/', carga_localidades, name='correr_loc'),
                      url(r'^turnolistar/$', login_required(TurnoListar.as_view()), name='turno_listar'),
                      url(r'^turnobrightspeed/', login_required(TurnoBrightspeed.as_view()), name='turno_brightspeed'),
                      url(r'^turnocrear/', login_required(TurnoCrear.as_view()), name='turno_crear'),
                      url(r'^turnoactualizar/(?P<pk>\d+)/$', login_required(views.TurnoActualizar.as_view()), name='turno_actualizar'),
                      url(r'^turnocrearpaciente/', views.crearpaciente_turno, name='turnopaciente_crear_ajax'),
                      url(r'^turnoactualizarpaciente/', views.actualizarpaciente_turno, name='turnopaciente_actualizar_ajax'),
                      url(r'^turnocrearpacientetemplate/', login_required(TurnoPacienteCrear.as_view()), name='turnopaciente_crear'), # para turno crear paciente
                      url(r'^turnocrearpacientetemplate2/', login_required(TurnoPacienteCrearModal.as_view()), name='turnopaciente_crear2'), # para el listdao de pacientes y historial
                      path('buscarpacientedatos/', views.buscar_paciente_datos, name='buscar_paciente_datos'),
                      path('buscarpacientedni/', views.buscar_paciente_dni, name='buscar_paciente_dni'),
                      path('buscarobrasocial/', views.buscar_obrasocial, name='buscar_obrasocial'),
                      path('buscarmedico/', views.buscar_medico, name='buscar_medico'),
                      path('buscarestablecimiento/', views.buscar_establecimiento, name='buscar_establecimiento'),
                      path('buscarturno/', views.buscar_turno, name='buscar_turno'),
                      path('buscarturnos_paciente/', views.buscar_turnosxpacienteid, name='buscar_turnoxpaciente'),
                      path('listapacientes/', views.paciente_listar, name='paciente_listar'),
                      path('listapacientesturnoid/', views.listarpaciente_turnoid, name='paciente_listarturnoid'),
                      path('listapacientesnormal/', views.paciente_listarnormal, name='paciente_listarnormal'),
                      path('listaobrasocial/', views.obrasocial_listar, name='obrasocial_listar'),
                      path('listamedicosderivantes/', views.medicosderivantes_listar, name='medicosderivantes_listar'),
                      path('listaestablecimientos/', views.establecimientos_listar, name='establecimientos_listar'),
                      path('actualizarturno/', views.actualizar_turno_fecha, name='actualizar_turno'),
                      path('actualizarturnoestado/', views.actualizar_turno_estado, name='actualizar_turno_estado'),
                      path('actualizarturnocortado/', views.actualizar_turno_cortado, name='actualizar_turno_cortado'),
                      path('consultatipoturno/', views.consulta_tipoturno, name='consulta_tipoturno'),
                      path('crearnota/', views.crearnota_turno, name='crear_nota'),
                      path('actualizarnota/', views.actualizarnota_turno, name='actualizar_nota'),
                      path('crearturnoreservado/', views.turnoreservado_crear, name='turnoreservado_crear'),
                      path('eliminarturnobloqueado/', views.turnobloqueado_eliminar, name='turnobloqueado_eliminar'),
                      url(r'^constanciaturnoimprimir/', constancia_turno_imprimir, name='turno_constanciaimprimir'),
                      url(r'^generar_linkimagenes/', generar_linkimagenes, name='generar_linkimagenes'),
                      path('crearferiado/', views.crear_feriado, name='crear_feriado'),
                      path('crearmedicoderivante/', views.medicoderivante_crear, name='crear_medicoderivante'),
                  ], 'turno')

turno/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db import models
from simple_history.models import HistoricalRecords

from tecnico.models import Insumo, InsumoLote


def user_directory_path_pm(instance, filename):
    return 'fotospmdoc/uid_{0}/pm/{1}'.format(instance.paciente.id, filename)


def user_directory_path_dni(instance, filename):
    return 'fotospmdoc/uid_{0}/dni/{1}'.format(instance.paciente.id, filename)


def user_directory_path_informe(instance, filename):
    return 'informes/uid_{0}/{1}'.format(instance.id, filename)


def user_directory_path_informe_audio(instance, filename):
    return 'audios/uid_{0}/informe_audio_{0}.wav'.format(instance.id)


class Pais(models.Model):
    class Meta:
        ordering = ['nombre']
    nombre = models.CharField(max_length=120)
    codigo = models.IntegerField()

    def __str__(self):
        return self.nombre


class Provincia(models.Model):
    class Meta:
        ordering = ['nombre']
    pais = models.ForeignKey(Pais, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=40)
    codigo = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.nombre


class Departamento(models.Model):
    class Meta:
        ordering = ['nombre']
    provincia = models.ForeignKey(Provincia, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=120)
    codigo = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.nombre


class Localidad(models.Model):
    class Meta:
        ordering = ['nombre']
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=120)
    codigo = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.nombre


class Barrio(models.Model):
    class Meta:
        ordering = ['nombre']
    nombre = models.CharField(max_length=160)
    codigo = models.IntegerField(unique=True)

    def __str__(self):
        return self.nombre


class MedicoDerivante(models.Model):
    class Meta:
        ordering = ['apellido', 'nombre']
    matricula = models.CharField(max_length=40, unique=True)
    nombre = models.CharField(max_length=80, null=True, blank=True)
    apellido = models.CharField(max_length=200)
    observacion = models.CharField(max_length=600, null=True, blank=True)
    telefono = models.CharField(max_length=40, null=True, blank=True)
    history = HistoricalRecords()

    def __str__(self):
        nombre_completo = ''
        if self.apellido:
            nombre_completo += self.apellido + ', '
        if self.nombre:
            nombre_completo += self.nombre
        return nombre_completo


class EstablecimientoDerivador(models.Model):
    ENABLE = (
        (True, 'Habilitado'),
        (False, 'Deshabilitado'),
    )
    TYPES = {
        ('Hospital', 'Hospital'),
        ('Clinica', 'Clinica')
    }

    class Meta:
        ordering = ['nombre']
    nombre = models.CharField(max_length=200, verbose_name='Nombre del Establecimiento')
    tipo = models.CharField(choices=TYPES, max_length=40, verbose_name='Tipo de institución', null=True)
    abreviatura = models.CharField(max_length=10, verbose_name='Abreviatura', null=True, blank=True)
    codigo = models.PositiveSmallIntegerField(verbose_name='Codigo del Establecimiento Derivador', unique=True)
    direccion = models.CharField(max_length=200,verbose_name='Dirección', null=True, blank=True)
    informacion_contacto = models.TextField(max_length=300, verbose_name='Información de contacto', null=True, blank=True)

    def __str__(self):
        return self.nombre


class EstablecimientoServicio(models.Model):
    ENABLE = (
        (True, 'Habilitado'),
        (False, 'Deshabilitado'),
    )

    class Meta:
        ordering = ['nombre']
    nombre = models.CharField(max_length=200, verbose_name='Nombre del Servicio ', null=True)
    observaciones = models.TextField(max_length=300, verbose_name='Información de contacto del Servicio', null=True, blank=True)

    def __str__(self):
        return self.nombre


class Servicio(models.Model):
    TYPES = {
        ('CT', 'CT'),
        ('MR', 'MR'),
        ('CR', 'CR')
    }
    SUCURSAL = {
        ('Salta', 'Salta'),
        ('Oran', 'Oran'),
        ('Cafayate', 'Cafayate'),
        ('Rosario de la Frontera', 'Rosario de la Frontera'),
        ('Embarcacion', 'Embarcacion'),
        ('Tartagal', 'Tartagal'),
    }

    class Meta:
        ordering = ['nombre']
    nombre = models.CharField(max_length=200, verbose_name='Nombre del Establecimiento', unique=True)
    nombre_completo = models.CharField(max_length=200, verbose_name='Nombre Completo', null=True, blank=True)
    direccion = models.CharField(max_length=200, verbose_name='Direccion sucursal', null=True, blank=True)
    tipo = models.CharField(choices=TYPES, max_length=40, verbose_name='Tipo de Equipo', null=True)
    sucursal = models.CharField(choices=SUCURSAL, max_length=40, verbose_name='Sucursal')
    observacion = models.TextField(max_length=400, verbose_name='Observacion', null=True, blank=True)
    aetitle = models.CharField(max_length=80, verbose_name='AE TITLE', null=True, blank=True)
    protocolo_count = models.IntegerField(null=True, blank=True)
    protocolo_prefix = models.CharField(max_length=50, null=True, blank=True)
    protocolo_label = models.CharField(max_length=50, null=True, blank=True)
    codigo = models.IntegerField(null=True, blank=True, unique=True)
    codigo_sistema_ant = models.IntegerField(null=True, blank=True, unique=True)
    protocolo_mesactual = models.SmallIntegerField(default=1) # aux para el reseteo del count de mes en protocolos
    hora_guardiaini = models.TimeField(null=True, blank=True)
    hora_guardiafin = models.TimeField(null=True, blank=True)
    informe_encabezado = models.CharField(max_length=300, null=True, blank=True) # texto info por servicio que se agrega al informe final
    prefix_access_number = models.CharField(max_length=25, null=True, blank=True) # prefijo para los access number de este servicio
    nro_informe_prefix = models.CharField(max_length=50, null=True, blank=True)
    nro_informe_count = models.IntegerField(null=True, blank=True, default=0)
    stock_insumo_general = models.BooleanField(default=False) # gestion del inusmo en forma general por servicio o en caso false seria por tecnico caso boedo
    encargado_stock = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True)
    usa_worklist_vm = models.BooleanField(default=False)
    usa_access_number = models.BooleanField(default=True)
    habilitado = models.BooleanField(default=True)
    is_servicio_externo = models.BooleanField(default=False)
    slot_duration = models.CharField(max_length=50, default='00:20:00')
    slot_labelinteval = models.CharField(max_length=50, default='00:20:00')
    snap_duration = models.CharField(max_length=50, default='00:20:00')
    default_event_duration = models.CharField(max_length=50, default='00:20:00')
    slot_duration_sabado = models.CharField(max_length=50, default='00:20:00')
    slot_labelinteval_sabado = models.CharField(max_length=50, default='00:20:00')
    snap_duration_sabado = models.CharField(max_length=50, default='00:20:00')
    default_event_duration_sabado = models.CharField(max_length=50, default='00:20:00')
    slot_duration_domingo = models.CharField(max_length=50, default='00:20:00')
    slot_labelinteval_domingo = models.CharField(max_length=50, default='00:20:00')
    snap_duration_domingo = models.CharField(max_length=50, default='00:20:00')
    default_event_duration_domingo = models.CharField(max_length=50, default='00:20:00')
    maxtime_gridweek = models.CharField(max_length=50, default='24:00:00')
    mintime_gridweek = models.CharField(max_length=50, default='00:00:00')
    maxtime_gridday = models.CharField(max_length=50, default='24:00:00')
    mintime_gridday = models.CharField(max_length=50, default='00:00:00')
    maxtime_sabado = models.CharField(max_length=50, default='24:00:00')
    mintime_sabado = models.CharField(max_length=50, default='00:00:00')
    maxtime_domingo = models.CharField(max_length=50, default='24:00:00')
    mintime_domingo = models.CharField(max_length=50, default='00:00:00')
    gridweek_weekends = models.CharField(max_length=50, default='false')

    def __str__(self):
        return self.nombre


class Obrasocial(models.Model):
    OS_ENABLE = (
        (True, 'Habilitada'),
        (False, 'Deshabilitada'),
    )
    OS_ACTIVA = (
        (True, 'SI'),
        (False, 'NO'),
    )

    class Meta:
        ordering = ['nombre']

    nombre = models.CharField(max_length=200, verbose_name='Nombre - Razon Social')
    cuit = models.CharField(max_length=40, verbose_name='Numero de CUIT', null=True, unique=True)
    servicio = models.ManyToManyField(Servicio)
    abreviatura = models.CharField(max_length=120, verbose_name='Abreviatura', null=True)
    codigo = models.IntegerField(verbose_name='Codigo interno Obra Social', null=True, unique=True)
    direccion = models.CharField(max_length=200,verbose_name='Dirección', null=True, blank=True)
    informacion_contacto = models.CharField(max_length=300, verbose_name='Información de contacto', null=True, blank=True)
    observacion = models.CharField(max_length=1000, verbose_name='Observacion', null=True, blank=True)
    habilitada = models.BooleanField(choices=OS_ENABLE, verbose_name='Estado', default=True, null=True)
    activa = models.BooleanField(choices=OS_ACTIVA, verbose_name='Activa', default=True)
    fecregistro = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación', null=True)
    fecactualizacion = models.DateTimeField(auto_now=True, verbose_name='Ultima actualización', null=True)
    history = HistoricalRecords()

    def __str__(self):
        return self.nombre


class ServicioEstudio(models.Model):

turno/templates/paciente/lista_opcion_departamento.html
<option value="">---------</option>
{% for dpto in departamentos %}
<option value="{{ dpto.pk }}">{{ dpto.nombre }}</option>
{% endfor %}

turno/templates/paciente/lista_opcion_localidad.html
<option value="">---------</option>
{% for loc in localidades %}
<option value="{{ loc.pk }}">{{ loc.nombre }}</option>
{% endfor %}

turno/templates/paciente/lista_opcion_provincia.html
<option value="">---------</option>
{% for pro in provincias %}
<option value="{{ pro.pk }}">{{ pro.nombre }}</option>
{% endfor %}

turno/templates/paciente/paciente_corregir_popup.html
<div class="modal-dialog">
    <div class="modal-content modal-form">
        <form method="post" action="{% url 'turno:pac_corregir_popup' object.pk %}">
            <div class="modal-header">
                <a class="btn btn-danger pull-right"  data-dismiss="modal" title="Cerrar" style="margin-left: 10px"><i class="fas fa-times"></i></a>
                <h3><strong>Paciente</strong> {{ object.apellido }}, {{ object.nombre }}</h3>
            </div>
            {% csrf_token %}
            <div class="table container">
                <div class="row">
                    <div class="col-xs-12">
                        {{ form.as_p }}
                        <a href="{% url 'turno:pac_corregir' %}" class="btn btn-danger pull-right">Cancelar</a>
                        <input type="submit" class="btn btn-success pull-right" style="margin-right: 10px" value="Guardar">
                    </div>
                    <div class="col-xs-6"></div>
                </div>
            </div>
        </form>

        <script>
            $('#id_fecnac').inputmask('dd/mm/yyyy', {
                'placeholder': 'dd/mm/yyyy'
            })
            $('#id_obrasocial').addClass('form-control');
            let atribute = "data-inputmask=\"'alias': 'dd/mm/yyyy'\" data-mask";
            $('#id_fecnac').addClass(atribute);
            $("#id_pais").change(function () {
                var paisId = $(this).val();
                $("#id_provincia").html('<option value="">---------</option>');
                $("#id_departamento").html('<option value="">---------</option>');
                $("#id_localidad").html('<option value="">---------</option>');

                $.ajax({
                    url: "{% url 'turno:correr_prov' %}",
                    data: {
                        'pais': paisId
                    },
                    success: function (data) {
                        $("#id_provincia").html(data);
                    }
                });
            });

            $("#id_provincia").change(function () {
                $("#id_departamento").html('<option value="">---------</option>');
                $("#id_localidad").html('<option value="">---------</option>');
                var provinId = $(this).val();

                $.ajax({
                    url: "{% url 'turno:correr_dpto' %}",
                    data: {
                        'provincia': provinId
                    },
                    success: function (data) {
                        $("#id_departamento").html(data);
                    }
                });
            });

            $("#id_departamento").change(function () {
                $("#id_localidad").html('<option value="">---------</option>');
                var deptoId = $(this).val();
                $.ajax({
                    url: "{% url 'turno:correr_loc' %}",
                    data: {
                        'departamento': deptoId
                    },
                    success: function (data) {
                        $("#id_localidad").html(data);
                    }
                });
            });
        </script>
    </div>
</div>

turno/templates/paciente/paciente_create.html
{% extends 'base.html' %}
{% load static %}

{% block css_app %}
    <link href="{% static 'dist/css/datatables/buttons.bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'dist/css/datatables/responsive.foundation.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'dist/css/datatables/dataTables.bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'dist/css/datatables/scroller.bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'static_turno/paciente/css/custom.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
    <div class="col-md-12 col-sm-12 col-xs-12 bg-white panel-body">
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Guardar">
            <a href="{% url 'turno:pac_listar' %}" class="text-black btn btn-default">Cancelar</a>
        </form>
    </div>
{% endblock %}

{% block js_app %}
    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/input-mask/jquery.inputmask.js' %}"></script>
    <script src="{% static 'plugins/input-mask/jquery.inputmask.date.extensions.js' %}"></script>
    <script src="{% static 'plugins/input-mask/jquery.inputmask.extensions.js' %}"></script>
    <script src="{% static 'bower_components/moment/min/moment.min.js' %}"></script>



    <script>
        $('#id_fecnac').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
        $('#id_obrasocial').addClass('form-control');
        let atribute = "data-inputmask=\"'alias': 'dd/mm/yyyy'\" data-mask";
        $('#id_fecnac').addClass(atribute);
        $("#id_pais").change(function () {
            var paisId = $(this).val();
            $("#id_provincia").html('<option value="">---------</option>');
            $("#id_departamento").html('<option value="">---------</option>');
            $("#id_localidad").html('<option value="">---------</option>');
            $.ajax({
                url: "{% url 'turno:correr_prov' %}",
                data: {
                    'pais': paisId
                },
                success: function (data) {
                    $("#id_provincia").html(data);
                }
            });
        });

        $("#id_provincia").change(function () {
            $("#id_departamento").html('<option value="">---------</option>');
            $("#id_localidad").html('<option value="">---------</option>');
            var provinId = $(this).val();

            $.ajax({
                url: "{% url 'turno:correr_dpto' %}",
                data: {
                    'provincia': provinId
                },
                success: function (data) {
                    $("#id_departamento").html(data);
                }
            });
        });

        $("#id_departamento").change(function () {
            $("#id_localidad").html('<option value="">---------</option>');
            var deptoId = $(this).val();

            $.ajax({
                url: "{% url 'turno:correr_loc' %}",
                data: {
                    'departamento': deptoId
                },
                success: function (data) {
                    $("#id_localidad").html(data);
                }
            });
        });
    </script>
{% endblock %}

turno/templates/paciente/paciente_delete.html
{% extends 'base.html' %}+
{% load static %}
{% block css_app %}
    <link href="{% static 'static_turno/paciente/css/custom.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
    <h4 >¿Desea Eliminar al paciente: <b>{{ object.apellido }}, {{object.nombre}}</b>?</h4>
    <div class="col-md-12 col-sm-12 col-xs-12 bg-white panel-body">
        <form method="post" >
            {% csrf_token %}
            <div class="form-group">
                <label>Identificación</label>
                <div class="input-bg-color" style="padding: 10px 10px;">
                    {{ object.identificacion_tipo }}: {{object.identificacion_numero}}
                </div>
            </div>
            <input type="submit" class="btn btn-primary" value="Eliminar">
            <a href="{% url 'turno:pac_listar' %}" class="text-black btn btn-default">Cancelar</a>
        </form>
    </div>

{% endblock %}

turno/templates/paciente/paciente_update.html
{% extends 'base.html' %}+
{% load static %}
{% block css_app %}
    <link rel="stylesheet" href="{% static 'plugins/datatables-actualizado/DataTables-1.10.20/css/dataTables.bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-actualizado/Buttons-1.6.1/css/buttons.bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-actualizado/Responsive-2.2.3/css/responsive.foundation.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-actualizado/Select-1.3.1/css/select.bootstrap.min.css' %}">
    <link href="{% static 'static_turno/paciente/css/custom.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
    <div class="col-md-6 col-sm-6 col-xs-6 bg-white panel-body">
        <form method="post" action="{% url 'turno:pac_actualizar' object.pk %}">
            {% csrf_token %}
            <div class="table container">
                <div class="row">
                    <div class="col-xs-12">
                        {{ form.as_p }}
                        <a href="{% url 'turno:turno_listar' %}" class="btn btn-danger pull-right">Cancelar</a>
                        <input type="submit" class="btn btn-success pull-right" style="margin-right: 10px" value="Guardar">
                    </div>
                    <div class="col-xs-6"></div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

{% block js_app %}
    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/input-mask/jquery.inputmask.js' %}"></script>
    <script src="{% static 'plugins/input-mask/jquery.inputmask.date.extensions.js' %}"></script>
    <script src="{% static 'plugins/input-mask/jquery.inputmask.extensions.js' %}"></script>
    <script src="{% static 'bower_components/moment/min/moment.min.js' %}"></script>

    <script>
        $('#id_fecnac').inputmask('dd/mm/yyyy', {
            'placeholder': 'dd/mm/yyyy'
        })

        $('#id_obrasocial').addClass('form-control');
        let atribute = "data-inputmask=\"'alias': 'dd/mm/yyyy'\" data-mask";
        $('#id_fecnac').addClass(atribute);
        $("#id_pais").change(function () {
            var paisId = $(this).val();
            $("#id_provincia").html('<option value="">---------</option>');
            $("#id_departamento").html('<option value="">---------</option>');
            $("#id_localidad").html('<option value="">---------</option>');

            $.ajax({
                url: "{% url 'turno:correr_prov' %}",
                data: {
                    'pais': paisId
                },
                success: function (data) {
                    $("#id_provincia").html(data);
                }
            });

        });

        $("#id_provincia").change(function () {
            $("#id_departamento").html('<option value="">---------</option>');
            $("#id_localidad").html('<option value="">---------</option>');
            var provinId = $(this).val();

            $.ajax({
                url: "{% url 'turno:correr_dpto' %}",
                data: {
                    'provincia': provinId
                },
                success: function (data) {
                    $("#id_departamento").html(data);
                }
            });

        });

        $("#id_departamento").change(function () {
            $("#id_localidad").html('<option value="">---------</option>');
            var deptoId = $(this).val();

            $.ajax({
                url: "{% url 'turno:correr_loc' %}",
                data: {
                    'departamento': deptoId
                },
                success: function (data) {
                    $("#id_localidad").html(data);
                }
            });
        });
    </script>
{% endblock %}