core/urls.py
from django.conf.urls import url
from django.urls import include
from .views import Home, change_password
from django.contrib.auth.decorators import login_required

app_name = 'core'

urlpatterns = [
    url(r'^$', login_required(Home.as_view()), name='home'),
    url(r'', include('django.contrib.auth.urls')),
    url(r'^password/$', change_password, name='change_password'),
]

turno/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views
from .views import *

app_name = 'turno'


turno_patterns = ([
                      url(r'^obrasociallistar/', login_required(ObrasocialListar.as_view()), name='obrasocial_list_view'),
                      url(r'^obrasocialcrear/$', login_required(ObrasocialCrear.as_view()), name='obrasocial_crear'),
                      url(r'^obrasocialeliminar/(?P<pk>\d+)/$', login_required(ObrasocialEliminar.as_view()), name='obrasocial_eliminar'),
                      url(r'^obrasocialactualizar/(?P<pk>\d+)/$', login_required(ObrasocialActualizar.as_view()), name='obrasocial_actualizar'),
                      url(r'^medicolistar/', login_required(MedicoListar.as_view()), name='med_listar'),
                      url(r'^medicocrear/$', login_required(MedicoCrear.as_view()), name='med_crear'),
                      url(r'^medicoactualizar/(?P<pk>\d+)/$', login_required(MedicoActualizar.as_view()), name='med_actualizar'),
                      url(r'^medicoeliminar/(?P<pk>\d+)/$', login_required(MedicoEliminar.as_view()), name='med_eliminar'),
                      url(r'^pacientelistar/', login_required(PacienteListar.as_view()), name='pac_listar'),
                      url(r'^pacientecrear/$', login_required(PacienteCrear.as_view()), name='pac_crear'),
                      url(r'^pacienteactualizar/(?P<pk>\d+)/$', login_required(PacienteActualizar.as_view()), name='pac_actualizar'),
                      url(r'^pacienteactualizarcorregir/(?P<pk>\d+)/$', login_required(PacienteCorregirPopUp.as_view()), name='pac_corregir_popup'),
                      url(r'^pacienteeliminar/(?P<pk>\d+)/$', login_required(PacienteEliminar.as_view()), name='pac_eliminar'),
                      url(r'^pacientecorregir/', login_required(PacienteCorregir.as_view()), name='pac_corregir'),
                      url(r'^pacientemarcarcorregido/', marcar_paciente_corregido, name='pac_marcar_corregido'),
                      path('ajax/carga_provincias/', carga_provincias, name='correr_prov'),
                      path('ajax/carga_departamentos/', carga_departamentos, name='correr_dpto'),
                      path('ajax/carga_localidades/', carga_localidades, name='correr_loc'),
                      url(r'^turnolistar/$', login_required(TurnoListar.as_view()), name='turno_listar'),
                      url(r'^turnobrightspeed/', login_required(TurnoBrightspeed.as_view()), name='turno_brightspeed'),
                      url(r'^turnocrear/', login_required(TurnoCrear.as_view()), name='turno_crear'),
                      url(r'^turnoactualizar/(?P<pk>\d+)/$', login_required(views.TurnoActualizar.as_view()), name='turno_actualizar'),
                      url(r'^turnocrearpaciente/', views.crearpaciente_turno, name='turnopaciente_crear_ajax'),
                      url(r'^turnoactualizarpaciente/', views.actualizarpaciente_turno, name='turnopaciente_actualizar_ajax'),
                      url(r'^turnocrearpacientetemplate/', login_required(TurnoPacienteCrear.as_view()), name='turnopaciente_crear'), # para turno crear paciente
                      url(r'^turnocrearpacientetemplate2/', login_required(TurnoPacienteCrearModal.as_view()), name='turnopaciente_crear2'), # para el listdao de pacientes y historial
                      path('buscarpacientedatos/', views.buscar_paciente_datos, name='buscar_paciente_datos'),
                      path('buscarpacientedni/', views.buscar_paciente_dni, name='buscar_paciente_dni'),
                      path('buscarobrasocial/', views.buscar_obrasocial, name='buscar_obrasocial'),
                      path('buscarmedico/', views.buscar_medico, name='buscar_medico'),
                      path('buscarestablecimiento/', views.buscar_establecimiento, name='buscar_establecimiento'),
                      path('buscarturno/', views.buscar_turno, name='buscar_turno'),
                      path('buscarturnos_paciente/', views.buscar_turnosxpacienteid, name='buscar_turnoxpaciente'),
                      path('listapacientes/', views.paciente_listar, name='paciente_listar'),
                      path('listapacientesturnoid/', views.listarpaciente_turnoid, name='paciente_listarturnoid'),
                      path('listapacientesnormal/', views.paciente_listarnormal, name='paciente_listarnormal'),
                      path('listaobrasocial/', views.obrasocial_listar, name='obrasocial_listar'),
                      path('listamedicosderivantes/', views.medicosderivantes_listar, name='medicosderivantes_listar'),
                      path('listaestablecimientos/', views.establecimientos_listar, name='establecimientos_listar'),
                      path('actualizarturno/', views.actualizar_turno_fecha, name='actualizar_turno'),
                      path('actualizarturnoestado/', views.actualizar_turno_estado, name='actualizar_turno_estado'),
                      path('actualizarturnocortado/', views.actualizar_turno_cortado, name='actualizar_turno_cortado'),
                      path('consultatipoturno/', views.consulta_tipoturno, name='consulta_tipoturno'),
                      path('crearnota/', views.crearnota_turno, name='crear_nota'),
                      path('actualizarnota/', views.actualizarnota_turno, name='actualizar_nota'),
                      path('crearturnoreservado/', views.turnoreservado_crear, name='turnoreservado_crear'),
                      path('eliminarturnobloqueado/', views.turnobloqueado_eliminar, name='turnobloqueado_eliminar'),
                      url(r'^constanciaturnoimprimir/', constancia_turno_imprimir, name='turno_constanciaimprimir'),
                      url(r'^generar_linkimagenes/', generar_linkimagenes, name='generar_linkimagenes'),
                      path('crearferiado/', views.crear_feriado, name='crear_feriado'),
                      path('crearmedicoderivante/', views.medicoderivante_crear, name='crear_medicoderivante'),
                  ], 'turno')

turno/views.py
import base64
import datetime
import io
import json
import locale
import os
import uuid

import pytz
import requests
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from dateutil.relativedelta import relativedelta
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.files.base import ContentFile
from django.db import transaction
from django.db.models import Q
from django.http import FileResponse
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.views.generic import ListView, DeleteView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, FormView
from reportlab.lib.pagesizes import LEGAL
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch, cm
from reportlab.pdfgen import canvas
from reportlab.platypus import Paragraph, Image, Frame

from .form import ObrasocialForm, MedicoForm, PacienteForm, TurnoForm, TurnoActualizarForm, TurnoPacienteForm, \
    TurnoPacienteFormModal
from .models import Obrasocial, MedicoDerivante, Pais, Provincia, Localidad, Departamento, Turno, \
    EstudioSolicitado, EstablecimientoDerivador, ServicioEstudio, TurnoNota, TurnoBloqueo, Servicio, Paciente, \
    TurnoReservado, Barrio, Feriados


class ObrasocialListar(ListView):
    model = Obrasocial
    template_name = 'obrasocial/obrasocial_list.html'


class ObrasocialCrear(CreateView):
    template_name = 'obrasocial/obrasocial_create.html'
    form_class = ObrasocialForm

    def get_success_url(self):
        return reverse('turno:obrasocial_list_view') + "?success_add"


class ObrasocialActualizar(UpdateView):
    model = Obrasocial
    form_class = ObrasocialForm
    template_name = 'obrasocial/obrasocial_update.html'

    def get_success_url(self):
        return reverse('turno:obrasocial_list_view') + "?success_update"


class ObrasocialEliminar(DeleteView):
    model = Obrasocial
    template_name = 'obrasocial/obrasocial_delete.html'

    def get_success_url(self):
        return reverse('turno:obrasocial_listar') + "?success_delete"


class MedicoListar(ListView):
    model = MedicoDerivante
    template_name = 'med_der/med_der_list.html'


class MedicoCrear(CreateView):
    template_name = 'med_der/med_der_create.html'
    form_class = MedicoForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return redirect(reverse_lazy('turno:med_listar') + "?error=matricula")

    def get_success_url(self):
        return reverse('turno:med_listar') + "?success_add"


class MedicoActualizar(UpdateView):
    model = MedicoDerivante
    form_class = MedicoForm
    template_name = 'med_der/med_der_update.html'

    def get_success_url(self):
        return reverse('turno:med_listar') + "?success_update"


class MedicoEliminar(DeleteView):
    model = MedicoDerivante
    template_name = 'med_der/med_der_delete.html'

    def get_success_url(self):
        return reverse('turno:med_listar') + "?success_delete"


class PacienteListar(ListView):
    model = Paciente
    template_name = 'paciente/paciente_list.html'


class PacienteCrear(CreateView):
    template_name = 'paciente/paciente_create.html'
    form_class = PacienteForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            result = 'error_create'
            return redirect(reverse('turno:pac_listar') + '?' + result)

    def get_success_url(self):
        return reverse('turno:pac_listar') + "?success_add"


class PacienteActualizar(UpdateView):
    model = Paciente
    form_class = PacienteForm
    template_name = 'paciente/paciente_update.html'

    def get_success_url(self):
        return reverse('turno:turno_listar') + "?success_update"


class PacienteEliminar(DeleteView):
    model = Paciente
    template_name = 'paciente/paciente_delete.html'

    def get_success_url(self):
        return reverse('turno:pac_listar') + "?success_delete"


class PacienteCorregir(ListView):
    model = Paciente
    template_name = 'paciente/paciente_list_corregir.html'

    def get_queryset(self):
        queryset = Paciente.objects.filter(corregir=True)
        return queryset


class PacienteCorregirPopUp(UpdateView):
    model = Paciente
    form_class = PacienteForm
    template_name = 'paciente/paciente_corregir_popup.html'

    def get_success_url(self):
        return reverse('turno:pac_corregir') + "?success_update"


@login_required
def carga_provincias(request):
    pais_codigo = request.GET.get('pais_codigo', '')
    select_html_provincias = '<option value = ""> --------- </option>'

    if pais_codigo != '':
        pais = Pais.objects.filter(codigo=pais_codigo).first()

        if pais:
            provincias = Provincia.objects.filter(pais=pais).order_by('nombre')
        else:
            provincias = ''

        for prov in provincias:
            select_html_provincias = select_html_provincias + '<option value = "' + str(
                prov.codigo) + '"> ' + prov.nombre + '</option>'

    response_data = {'provincias': select_html_provincias}

    return JsonResponse(response_data)


@login_required
def carga_departamentos(request):
    provincia_codigo = request.GET.get('provincia_codigo', '')
    select_html_departamentos = '<option value = ""> --------- </option>'

    if provincia_codigo != '':
        provincia = Provincia.objects.filter(codigo=provincia_codigo).first()
        if provincia:
            departamentos = Departamento.objects.filter(provincia=provincia).order_by('nombre')
        else:
            departamentos = ''

        for dpto in departamentos:
            select_html_departamentos = select_html_departamentos + '<option value = "' + str(
                dpto.codigo) + '"> ' + dpto.nombre + '</option>'
    response_data = {'departamentos': select_html_departamentos}

    return JsonResponse(response_data)


@login_required
def carga_localidades(request):
    departamento_codigo = request.GET.get('departamento_codigo', '')
    provincia_codigo = request.GET.get('provincia_codigo', '')
    pais_codigo = request.GET.get('pais_codigo', '')
    select_html_localidades = '<option value = ""> --------- </option>'

    if pais_codigo != '' and provincia_codigo != '' and departamento_codigo != '':
        pais = Pais.objects.filter(codigo=pais_codigo).first()
        provincia = Provincia.objects.filter(codigo=provincia_codigo, pais=pais).first()
        departamento = Departamento.objects.filter(codigo=departamento_codigo,provincia=provincia ).first()
        if departamento:
            localidades = Localidad.objects.filter(departamento=departamento).order_by('nombre')
        else:
            localidades = ''

        for loca in localidades:
            select_html_localidades = select_html_localidades + '<option value = "' + str(
                loca.codigo) + '"> ' + loca.nombre + '</option>'
    response_data = {'localidades': select_html_localidades}

    return JsonResponse(response_data)


@login_required
def consulta_barrio_codigoxid(request):
    barriocodigo = request.GET.get('barrio_codigo')
    barrio = Barrio.objects.filter(codigo=barriocodigo).first()
    if barrio:
        barrioid = barrio.id
    else:
        barrioid = 0
    response_data = {'barrioid': barrioid}

    return JsonResponse(response_data)


@login_required
def consulta_barrio_idxcodigo(request):
    barrioid = request.GET.get('barrio_id')
    barrio = Barrio.objects.filter(id=barrioid).first()
    codigo = str(barrio.codigo)
    response_data = {'barrio_codigo': codigo}

    return JsonResponse(response_data)



@login_required
def constancia_turno_imprimir(request):
    turnoid = request.GET.get('turnoid', '')
    obj_turno = Turno.objects.get(id=turnoid)
    paciente_nombre = obj_turno.paciente.nombre if obj_turno.paciente.nombre else ''
    paciente_apellido = obj_turno.paciente.apellido if obj_turno.paciente.apellido else ''
    pacientenombrecompleto = paciente_apellido + '_' + paciente_nombre + '.pdf'
    pacientenombrecompleto2 = paciente_apellido + ', ' + paciente_nombre
    filename = paciente_apellido + '_' + paciente_nombre
    buffer = io.BytesIO()
    w = LEGAL[0]
    h = LEGAL[1]
    ps = (w, h)
    c = canvas.Canvas(buffer, pagesize=ps)
    c.rect(0.4 * cm, 18.21 * cm, w - 0.8 * cm, (h / 2) - 0.8 * cm)
    x = 0.4 * cm
    y = h - 2 * cm
    xfin = w - 0.4 * cm

    logo = 'static/dist/img/tc.png'
    im = Image(logo, 102, 43)
    x_imagen = 0.42 * cm
    y_imagen = h - 1.63 * cm
    im.drawOn(c, x_imagen, y_imagen - 8)

    c.setFont('Helvetica', 16)
    c.drawString((w / 2) - 70, h - 1.2 * cm, "CONSTANCIA DE TURNO")
    c.setFont('Helvetica', 7)
    c.drawString(w - 115, h - 0.7 * cm, "TOMOGRAFIA COMPUTADA")
    c.drawString(w - 110, h - 1 * cm, "SOCIEDAD DEL ESTADO")
    c.drawString(w - 115, h - 1.3 * cm, "Mariano Boedo 151 - 4400-Salta")
    c.drawString(w - 98, h - 1.6 * cm, "Tel: 0387-4215342")
    c.line(x, y + 2, xfin, y + 2)

    c.setFont('Helvetica-Bold', 13)
    c.drawString(x_imagen + 4, y_imagen - 28, "Servicio:")
    c.setFont('Helvetica-Bold', 20)
    c.drawString(x_imagen + 61, y_imagen - 28, obj_turno.servicio.nombre_completo)

    server_timezone = pytz.timezone("America/Argentina/Salta")
    f = obj_turno.fechahora_inicio.astimezone(server_timezone)
    dias = {"Monday": "Lunes", "Tuesday": "Martes", "Wednesday": "Miércoles", "Thursday": "Jueves", "Friday": "Viernes",
            "Saturday": "Sábado", "Sunday": "Domingo"}

turno/templates/med_der/med_der_create.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <form role="form" action="{% url 'turno:med_crear' %}" method="post">
            <div class="modal-header">
                <a class="btn btn-danger pull-right"  data-dismiss="modal" title="Cerrar" style="margin-left: 10px"><i class="fas fa-times"></i></a>
                <h3>Crear Médico</h3>
            </div>
            <div class="modal-body">
                {% csrf_token %}
                <div class="panel panel-default">
                    <div class="panel-body">
                        {{ form.as_p }}
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="col-lg-12 text-right">
                    <button type="submit" class="btn btn-success pull-right " style="margin-right: 10px" > <strong>Guardar</strong></button>
                </div>
            </div>
        </form>
    </div>
</div>

turno/templates/med_der/med_der_delete.html
{% extends 'base.html' %}+
{% load static %}
{% block css_app %}
    <link href="{% static 'static_turno/med_der/css/custom.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
    <h4 >¿Desea eliminar al médico: <b>{{ object.name }}</b>?</h4>
    <div class="col-md-12 col-sm-12 col-xs-12 bg-white panel-body">
        <form method="post" >
            {% csrf_token %}

            <div class="form-group">
                <label>Apellido</label>
                <div class="input-bg-color" style="padding: 10px 10px;">
                    {{ object.apellido }}
                </div>
            </div>
            <div class="form-group">
                <label>Nombre</label>
                <div class="input-bg-color" style="padding: 10px 10px;">
                    {{ object.nombre }}
                </div>
            </div>
            <div class="form-group">
                <label>Matrícula</label>
                <div class="input-bg-color" style="padding: 10px 10px;">
                    {{ object.matricula }}
                </div>
            </div>
            <input type="submit" class="btn btn-primary" value="Eliminar">
            <a href="{% url 'turno:med_listar' %}" class="text-black btn btn-default">Cancelar</a>
        </form>
    </div>

{% endblock %}

turno/templates/med_der/med_der_list.html
{% extends 'base.html' %}
{% load static %}

{% block css_app %}
    <link rel="stylesheet" href="{% static 'plugins/datatables-actualizado/DataTables-1.10.20/css/dataTables.bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-actualizado/Buttons-1.6.1/css/buttons.bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-actualizado/Responsive-2.2.3/css/responsive.foundation.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-actualizado/Select-1.3.1/css/select.bootstrap.min.css' %}">
    <link href="{% static 'static_turno/med_der/css/custom.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
    <div id='panel-table' class="col-md-12 col-sm-12 col-xs-12  panel" style="opacity: 0">
        <br>

        <div class="box-body">
            <div class="table-responsive">
                <a onclick="return abrir_modal('{% url 'turno:med_crear' %}')" class="btn btn-success"><i class="fa fa-plus" style="color: white"></i></a>
                <table style="width: 100%" id="data-table-full" class="table table-bordered table-striped text-center table-condensed table-small-font" >
                    <h3>Listado de médicos</h3>
                    <style> h3 {text-align: center;}</style>
                    <style> h3 {
                        color: #31708f;;
                    }</style>
                    <thead>
                    <tr>
                        <th class="text-center all">Matrícula</th>
                        <th class="text-center all">Apellido y Nombre</th>
                        <th class="text-center all">Email</th>
                        <th class="text-center all">Teléfono</th>
                        <th class="text-center all">Modificar</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if object_list %}
                        {% for med in object_list %}
                            <tr>
                                <td class="text-center">{{med.matricula}}</td>
                                <td class="text-center">{{med.apellido}}</td>
                                <td class="text-center">{{med.observacion|default_if_none:"---"}}</td>
                                <td class="text-center">{{med.telefono|default_if_none:"---"}}</td>
                                <td class="text-center">
                                    <div >
                                        <a onclick="return abrir_modal('{% url 'turno:med_actualizar' med.id %}')" class="btn-sm btn-warning"><i class="fa fa-edit"></i></a>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div id="ventana_modal" class="modal fade" role="dialog"></div>
{% endblock %}

{% block js_app %}
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.bootstrap.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/buttons.bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/vfs_fonts.js' %}"></script>
    <script src="{% static 'plugins/datatables/buttons.html5.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/buttons.print.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.keyTable.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/responsive.bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.scroller.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.select.min.js' %}"></script>
    <script src="{% static 'static_turno/med_der/js/datatables.init.js' %}"></script>
    <script>
        window.onload = function () { document.getElementById("panel-table").style["opacity"] = "1";}
    </script>

    <script>
        function abrir_modal(url)
        {
            $('#ventana_modal').load(url, function()

            {
                $(this).modal({
                    backdrop: 'static',
                    keyboard: false
                });
                $(this).modal('show');
            });
            return false;
        }

        function cerrar_modal()
        {
            $('#ventana_modal').modal('hide');
            return false;
        }
    </script>
    <script>
        {% if  request.GET.error == "matricula" %}
            iziToast.question({
                timeout: 3000,
                close: false,
                overlay: true,
                displayMode: 'once',
                id: 'question',
                zindex: 999,
                title: 'No se pudo crear o editar médico. Matrícula repetida',
                position: 'center',
                color: 'red',
            });
        {% endif %}
    </script>
{% endblock %}

turno/templates/med_der/med_der_update.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <form method="post" action="{% url 'turno:med_actualizar' object.pk %}">
            <div class="modal-header">
                <a class="btn btn-danger pull-right"  data-dismiss="modal" title="Cerrar" style="margin-left: 10px"><i class="fas fa-times"></i></a>
                <h3>Modificar Médico</h3>
            </div>
            <div class="modal-body">
                {% csrf_token %}
                <div class="panel panel-default">
                    <div class="panel-body">
                        {{ form.as_p }}
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="col-lg-12 text-right">
                    <button type="submit" class="btn btn-success pull-right " style="margin-right: 10px" > <strong>Guardar</strong></button>
                </div>
            </div>
        </form>
    </div>
</div>