core/urls.py
from django.conf.urls import url
from django.urls import include
from .views import Home, change_password
from django.contrib.auth.decorators import login_required

app_name = 'core'

urlpatterns = [
    url(r'^$', login_required(Home.as_view()), name='home'),
    url(r'', include('django.contrib.auth.urls')),
    url(r'^password/$', change_password, name='change_password'),
]

informe/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from .views import *
from django.contrib.auth.decorators import login_required

app_name = 'informe'


informe_patterns = ([
    path('list_pendientes/', login_required(InformeListar.as_view()), name='inf_listar'),
    path('list_pendientes_medico/', login_required(InformeListarMedico.as_view()), name='inf_listarmedico'),
    path('list_firmar/', login_required(InformeFirmar.as_view()), name='inf_listarfirmar'),
    path('informe_generar/', views.informe_medico_pdf, name='inf_informegenerar'),
    url(r'^informe_crear/(?P<pk>\d+)/$', login_required(InformeCrear.as_view()), name='inf_crear'),
    url(r'^informe_crearmedico/(?P<pk>\d+)/$', login_required(InformeCrearMedico.as_view()), name='inf_crearmedico'),
    url(r'^informe_subirfirmado/(?P<pk>\d+)/$', login_required(InformeSubirFirmado.as_view()),
        name='inf_subirfirmado'),
    url(r'^preinforme/(?P<pk>\d+)/$', login_required(PreInformeCrear.as_view()), name='inf_preinforme'),
    path('ajax/medicomatricula/', views.medicomatricula, name='ajaxmedicomatricula'),
    path('batch/exportarinformes/', views.exportar_informes, name='exportarinformes'),

    path('ajax/grabaraudio/', views.grabaraudio, name='ajaxgrabaraudio'),
    path('informe/corregirpaciente/', views.corregirpaciente, name='corregirpaciente'),
    path('informe/corregirtexto/', views.traer_texto_corregir, name='traertexto'),
    path('informe/corregirestudio/', views.corregirestudio, name='corregirestudio'),
    path('informe/corregirtextoestudio/', views.traer_texto_corregir_estudio, name='traertextoestudio'),
    path('informe/cambiarfirmadodigital/', views.finalizar_sinfirma, name='finalizar_sinfirma'),
    path('informe/estadisticamensual/', views.estadisticas_excel, name='estadisticas_excel'),
    path('informe/imprimiretiqueta/', views.imprimir_etiqueta, name='imprimir_etiqueta'),
    path('consultarplantillas/', views.consultar_plantillas, name='consultar_plantillas'),
    path('informeteccorregido/', views.informe_tec_correccion_finalizada, name='informe_tec_corregido'),
    path('medicoscountmes/', views.medicos_count_mes, name='medicos_count_mes'),
    path('informecorecciontexto/', views.InformeCorregir, name='informe_corregir'),
    path('tipeoenuso/', views.tipeo_marcar_enuso, name='tipeo_en_uso'),
    path('informecerrarexpediente/', login_required(CerrarExpediente.as_view()), name='cerrar_expediente'),
    path('unificarPaciente/', views.unificar_paciente_index, name='unificar_paciente'),
    path('unificarPacienteHC/', views.unificar_paciente_hc, name='unificar_paciente_hc'),
    path('cerrarexpediente/', views.cerrar_expediente_sin_informe, name='cerrar_expediente_sin_informe'),
    ], 'informe')

turno/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views
from .views import *

app_name = 'turno'


turno_patterns = ([
                      url(r'^obrasociallistar/', login_required(ObrasocialListar.as_view()), name='obrasocial_list_view'),
                      url(r'^obrasocialcrear/$', login_required(ObrasocialCrear.as_view()), name='obrasocial_crear'),
                      url(r'^obrasocialeliminar/(?P<pk>\d+)/$', login_required(ObrasocialEliminar.as_view()), name='obrasocial_eliminar'),
                      url(r'^obrasocialactualizar/(?P<pk>\d+)/$', login_required(ObrasocialActualizar.as_view()), name='obrasocial_actualizar'),
                      url(r'^medicolistar/', login_required(MedicoListar.as_view()), name='med_listar'),
                      url(r'^medicocrear/$', login_required(MedicoCrear.as_view()), name='med_crear'),
                      url(r'^medicoactualizar/(?P<pk>\d+)/$', login_required(MedicoActualizar.as_view()), name='med_actualizar'),
                      url(r'^medicoeliminar/(?P<pk>\d+)/$', login_required(MedicoEliminar.as_view()), name='med_eliminar'),
                      url(r'^pacientelistar/', login_required(PacienteListar.as_view()), name='pac_listar'),
                      url(r'^pacientecrear/$', login_required(PacienteCrear.as_view()), name='pac_crear'),
                      url(r'^pacienteactualizar/(?P<pk>\d+)/$', login_required(PacienteActualizar.as_view()), name='pac_actualizar'),
                      url(r'^pacienteactualizarcorregir/(?P<pk>\d+)/$', login_required(PacienteCorregirPopUp.as_view()), name='pac_corregir_popup'),
                      url(r'^pacienteeliminar/(?P<pk>\d+)/$', login_required(PacienteEliminar.as_view()), name='pac_eliminar'),
                      url(r'^pacientecorregir/', login_required(PacienteCorregir.as_view()), name='pac_corregir'),
                      url(r'^pacientemarcarcorregido/', marcar_paciente_corregido, name='pac_marcar_corregido'),
                      path('ajax/carga_provincias/', carga_provincias, name='correr_prov'),
                      path('ajax/carga_departamentos/', carga_departamentos, name='correr_dpto'),
                      path('ajax/carga_localidades/', carga_localidades, name='correr_loc'),
                      url(r'^turnolistar/$', login_required(TurnoListar.as_view()), name='turno_listar'),
                      url(r'^turnobrightspeed/', login_required(TurnoBrightspeed.as_view()), name='turno_brightspeed'),
                      url(r'^turnocrear/', login_required(TurnoCrear.as_view()), name='turno_crear'),
                      url(r'^turnoactualizar/(?P<pk>\d+)/$', login_required(views.TurnoActualizar.as_view()), name='turno_actualizar'),
                      url(r'^turnocrearpaciente/', views.crearpaciente_turno, name='turnopaciente_crear_ajax'),
                      url(r'^turnoactualizarpaciente/', views.actualizarpaciente_turno, name='turnopaciente_actualizar_ajax'),
                      url(r'^turnocrearpacientetemplate/', login_required(TurnoPacienteCrear.as_view()), name='turnopaciente_crear'), # para turno crear paciente
                      url(r'^turnocrearpacientetemplate2/', login_required(TurnoPacienteCrearModal.as_view()), name='turnopaciente_crear2'), # para el listdao de pacientes y historial
                      path('buscarpacientedatos/', views.buscar_paciente_datos, name='buscar_paciente_datos'),
                      path('buscarpacientedni/', views.buscar_paciente_dni, name='buscar_paciente_dni'),
                      path('buscarobrasocial/', views.buscar_obrasocial, name='buscar_obrasocial'),
                      path('buscarmedico/', views.buscar_medico, name='buscar_medico'),
                      path('buscarestablecimiento/', views.buscar_establecimiento, name='buscar_establecimiento'),
                      path('buscarturno/', views.buscar_turno, name='buscar_turno'),
                      path('buscarturnos_paciente/', views.buscar_turnosxpacienteid, name='buscar_turnoxpaciente'),
                      path('listapacientes/', views.paciente_listar, name='paciente_listar'),
                      path('listapacientesturnoid/', views.listarpaciente_turnoid, name='paciente_listarturnoid'),
                      path('listapacientesnormal/', views.paciente_listarnormal, name='paciente_listarnormal'),
                      path('listaobrasocial/', views.obrasocial_listar, name='obrasocial_listar'),
                      path('listamedicosderivantes/', views.medicosderivantes_listar, name='medicosderivantes_listar'),
                      path('listaestablecimientos/', views.establecimientos_listar, name='establecimientos_listar'),
                      path('actualizarturno/', views.actualizar_turno_fecha, name='actualizar_turno'),
                      path('actualizarturnoestado/', views.actualizar_turno_estado, name='actualizar_turno_estado'),
                      path('actualizarturnocortado/', views.actualizar_turno_cortado, name='actualizar_turno_cortado'),
                      path('consultatipoturno/', views.consulta_tipoturno, name='consulta_tipoturno'),
                      path('crearnota/', views.crearnota_turno, name='crear_nota'),
                      path('actualizarnota/', views.actualizarnota_turno, name='actualizar_nota'),
                      path('crearturnoreservado/', views.turnoreservado_crear, name='turnoreservado_crear'),
                      path('eliminarturnobloqueado/', views.turnobloqueado_eliminar, name='turnobloqueado_eliminar'),
                      url(r'^constanciaturnoimprimir/', constancia_turno_imprimir, name='turno_constanciaimprimir'),
                      url(r'^generar_linkimagenes/', generar_linkimagenes, name='generar_linkimagenes'),
                      path('crearferiado/', views.crear_feriado, name='crear_feriado'),
                      path('crearmedicoderivante/', views.medicoderivante_crear, name='crear_medicoderivante'),
                  ], 'turno')

informe/models.py
from django.db import models
from django.contrib.auth.models import User
from turno.models import Servicio
from ckeditor.fields import RichTextField

TYPES = {
    ('CT', 'CT'),
    ('MR', 'MR'),
    ('CR', 'CR')
}


class InformePlanilla(models.Model):
    class Meta:
        ordering = ['medico', 'prestacion_codigo', 'texto_numero']
    servicio_tipo = models.CharField(choices=TYPES, max_length=40, verbose_name='Tipo de Equipo', null=True)
    medico = models.ForeignKey(User, on_delete=models.PROTECT)
    prestacion_codigo = models.CharField(max_length=60)
    texto_titulo = models.CharField(max_length=120, blank=True, null=True)
    habilitada = models.BooleanField(default=True)
    texto = RichTextField(null=True, blank=True)
    texto_numero = models.IntegerField()

    def __str__(self):
        return self.medico.username + ' - ' + self.prestacion_codigo + ' - ' + 'Nº: ' + str(self.texto_numero)


class UnificarPaciente(models.Model):
    listado_nro_orden = models.CharField(max_length=2000, null=True, blank=True)
    paciente_borrado_id_label = models.CharField(max_length=500,null=True, blank=True)
    paciente_borrado_nn = models.BooleanField(default=False)
    motivo = models.CharField(max_length=1000, null=True, blank=True)
    usuario = models.ForeignKey(User, on_delete=models.PROTECT)
    fecha_registro = models.DateTimeField(auto_now_add=True)


class InformePlanillaDBTCSE(models.Model):
    prestacion_codigo = models.CharField(max_length=60, null=True, blank=True)
    medico_matricula = models.CharField(max_length=60, null=True, blank=True)
    habilitada = models.CharField(max_length=20, null=True, blank=True)
    texto = RichTextField(null=True, blank=True)
    texto_numero = models.CharField(max_length=10, null=True, blank=True)

informe/forms.py
from django import forms
from turno.models import Turno


class InformeAltaForm(forms.ModelForm):
    class Meta:
        model = Turno
        fields = [
            'paciente',
            'medico_derivante',
            'obrasocial',
            'contrasteev',
            'contrastevo',
            'anestesia',
            'urgencia',
            'internado',
            'edadregistro_manual',
            'informe_pre_observaciones',
            'establecimiento_derivador'
        ]
        widgets = {
            'paciente': forms.TextInput(attrs={'class': 'form-control', 'id': 'f_pacienteid'}),
            'urgencia': forms.CheckboxInput(attrs={'id': 'f_urgencia', }),
            'internado': forms.CheckboxInput(attrs={'id': 'f_internado', }),
            'contrastevo': forms.CheckboxInput(attrs={'id': 'f_contrastevo', }),
            'contrasteev': forms.CheckboxInput(attrs={'id': 'f_contrasteev', }),
            'anestesia': forms.CheckboxInput(attrs={'id': 'f_anestesia', 'disabled': ''}),
            'obrasocial': forms.Select(attrs={'class': 'form-control', 'id': 'f_obrasocial', 'disabled':''}),
            'edadregistro_manual': forms.TextInput(
                attrs={'class': 'form-control', 'readonly': '', 'id': 'f_edadregistro', 'data-inputmask': "'alias': 'age'", 'data-mask': ''}),
            'informe_pre_observaciones': forms.Textarea(
                attrs={'class': 'form-control', 'style': 'resize: none;', 'rows': '2'}),
            'medico_derivante': forms.Select(attrs={'class': 'form-control', 'id': 'f_medico_derivante'}),
            'establecimiento_derivador': forms.Select(attrs={'class': 'form-control', 'id': 'f_establecimiento_derivador'}),
        }


class InformeCrearForm(forms.ModelForm):
    class Meta:
        model = Turno
        fields = [
            'informe_texto',
            'informe_observaciones',
            'informe_observaciones_tipeo'
        ]
        widgets = {
            'informe_texto': forms.Textarea(attrs={'class': 'form-control', 'id': 'textoinforme'}),
            'informe_observaciones': forms.Textarea(attrs={'class': 'form-control', 'style': 'resize: none;', 'rows': '3',}),
            'informe_observaciones_tipeo': forms.Textarea(
                attrs={'class': 'form-control', 'style': 'resize: none;', 'rows': '3', }),
        }


class InformeSubirFirmadoForm(forms.ModelForm):
    class Meta:
        model = Turno
        fields = [
            'informe_firmadopdf',
        ]

informe/templates/informe/informe_cerrar_expediente.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="div col-sm-12 panel">
        <h3 class="text-center margin-bottom">Finalizar expediente sin informe</h3>
        <div class="row margin pull-right" >
            <input class="input-sm" type="number" min="1" step="1" id="input-turnoid" placeholder="Buscar por Nº de Orden"/>
            <button type="button" class="btn-sm btn-info btn-flat" id="btn-buscarturno">
                <strong>Buscar Expediente</strong>
            </button>
        </div>

        <div class="row margin">
            <table class="table table-small-font table-sm table-bordered"  >
                <thead style="background: #D6EAF8">
                <tr>
                    <th class="text-center" colspan="2">
                            <span id="table-head"> Expediente Nº Orden:
                                <input class="input-sm " size="5" id="turno_id_cerrar_expediente" readonly />
                            </span>
                    </th>
                </tr>
                </thead>
                <tbody >
                <tr>
                    <td><strong>Paciente Nº Identificación</strong></td>
                    <td><span id="pac-id"></span></td>
                </tr>
                <tr>
                    <td><strong>Paciente Apellido/s</strong></td>
                    <td><span id="pac-apellido"></span></td>
                </tr>

                <tr>
                    <td><strong>Paciente Nombre/s</strong></td>
                    <td><span id="pac-nombre"></span></td>
                </tr>
                <tr>
                    <td><strong>Paciente Sexo</strong></td>
                    <td><span id="pac-sexo"></span></td>
                </tr>
                <tr>
                    <td><strong>Fecha del Estudio</strong></td>
                    <td><span id="fechaestudio"></span></td>
                </tr>
                <tr>
                    <td><strong>Estudios Solicitados</strong></td>
                    <td><span id="estudiossol"></span></td>
                </tr>
                <tr>
                    <td><strong>Técnico Radiólogo</strong></td>
                    <td><span id="estudiotecnico"></span></td>
                </tr>
                <tr>
                    <td><strong>Estado (Proceso Técnico)</strong></td>
                    <td><span id="estudioestado"></span></td>
                </tr>
                <tr>
                    <td><strong>Estado (Informe)</strong></td>
                    <td><span id="informeestado"></span></td>
                </tr>
                </tbody>
            </table>
            <div>
                <label class="text-danger">*Motivo para finalizar el expediente sin informe</label>
                <br>
                <input  class="input-sm" id="input-cierre-motivo" type="text" maxlength="999" size="100">
            </div>
            <a class="btn-danger btn margin-bottom pull-right"
               style="margin-top: 20px" id="btn-cerrarexpediente">
                <strong>Finalizar expediente sin Informe</strong>
            </a>
        </div>
    </div>
    </div>
{% endblock %}

{% block js_app %}
    <script>
        $('#btn-buscarturno').on('click', function() {
            const turnoid = 'R' + $('#input-turnoid').val().trim();
            if (turnoid !== 'R') {
                $.ajax({
                    type: 'get',
                    url: "{% url 'turno:buscar_turno' %}",
                    data:
                        {
                            'turno_buscar': turnoid
                        },
                    success: function (data)
                    {
                        if(data['error_404'] === '') {
                            $('#turno_id_cerrar_expediente').val(data['turno_id'])
                            $('#pac-id').text('(' + data['paciente_tipoid'] + ')' + data['paciente_dni'])
                            $('#pac-apellido').text(data['paciente_apellido'])
                            $('#pac-nombre').text(data['paciente_nombre'])
                            $('#pac-sexo').text(data['paciente_sexo'])
                            $('#fechaestudio').text(data['fechaini_string'])
                            $('#estudiossol').text(data['estudios_sol_string'])
                            $('#estudioestado').text(data['estudio_estado'])
                            $('#estudiotecnico').text(data['tecnico'])
                            $('#informeestado').text(data['estado_informe'])
                        }
                        else {
                            alert('No se encontró un expediente relacionado al Nº de Orden solicitado.')
                        }
                    },
                    error: function () {
                        alert("Error: No se pudo completar la operación.");
                    }
                });
            }
        });

        $('#btn-cerrarexpediente').on('click', function() {
            const estado_informe = $('#informeestado').text();
            const estado_estudio = $('#estudioestado').text();

            if (estado_informe=== 'Sin Informe' && estado_estudio !== 'Estudio No Realizado') {
                cerrar_informe()
            } else if (estado_estudio === 'Estudio No Realizado') {
                alert('No se puede completar la acción: El estudio no fue procesado por el Técnico Rad. (Estudio no realizado)')
            } else if (estado_informe === 'Informe Finalizado') {
                alert('No se puede completar la acción: El expediente ya tiene un informe finalizado por el médico')
            } else if (estado_informe=== 'Finalizado sin Informe') {
                alert('El expediente ya se encuentra "Finalizado sin Informe"')
            }

        });

        function cerrar_informe () {
            const turnoid = $('#turno_id_cerrar_expediente').val();
            const motivo_cierre = $('#input-cierre-motivo').val();
            if (turnoid.trim() !== '' && motivo_cierre.trim() !== '') {
                $.ajax({
                    headers:{'X-CSRFToken':'{{ csrf_token }}'},
                    dataType: 'json',
                    type: 'post',
                    url: "{% url 'informe:cerrar_expediente_sin_informe' %}",
                    data:
                        {
                            'turno_id': turnoid,
                            'motivo_cierre': motivo_cierre
                        },
                    success: function (data)
                    {
                        if(data['expediente_cerrado'] === true) {
                            location.replace("{% url 'informe:cerrar_expediente' %}?cerradoexito");
                        }
                        else {
                            alert('Error: No se pudo completar la operación.')
                        }
                    },
                    error: function () {
                        alert("Error: No se pudo completar la operación.");
                    }
                });
            } else {
                alert('Ingrese el Nº de Orden y el motivo para la finalización del expediente.')
            }
        }
        {% if 'cerradoexito' in request.GET %}
            alert('El expediente fue finalizado sin informe.')
        {% endif %}
    </script>
{% endblock %}

informe/templates/informe/informe_editar.html
{% extends 'base.html' %}
{% load static %}

{% block css_app %}
    <link href="{% static 'dist/css/datatables/buttons.bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'dist/css/datatables/responsive.foundation.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'dist/css/datatables/dataTables.bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'dist/css/dataeventeventtables/scroller.bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'static_turno/paciente/css/custom.css' %}" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <link href="{% static 'static_informe/ckeditor/css/custom_ckeditor.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <div id='panel-table' class="col-md-12 col-sm-12 col-xs-12  panel" style="opacity: 0">
        <h2>Editar Informe</h2>
        <div class="container">
            <div class="row text-center">
                <div class="col-md-2">
                    <a onclick="ajaxTraerTexto('1')" class="btn btn-info"><b>Texto 1</b></a>
                </div>
                <div class="col-md-2">
                    <a onclick="ajaxTraerTexto('2')" class="btn btn-info"><b>Texto 2</b></a>
                </div>
                <div class="col-md-2">
                    <a onclick="ajaxTraerTexto('3')" class="btn btn-info"><b>Texto 3</b></a>
                </div>
                <div class="col-md-2">
                    <a onclick="ajaxTraerTexto('4')" class="btn btn-info"><b>Texto 4</b></a>
                </div>
                <div class="col-md-4"></div>
            </div>
        </div>
        <div class=Container>
            <div class="row">
                <div class="col-md-9 mx-auto">
                    <form method="post">{% csrf_token %}
                        <br>
                        {{ form.as_p }}
                        <input type="submit" class="btn btn-primary" name="editar" value="Editar">
                        <a href="{% url 'informe:inf_listar' %}" class="text-black btn btn-default">Cancelar</a>
                        <input type="submit" class="btn btn-danger" name="finalizar" value="Finalizar">
                    </form>
                </div>

            </div>
            <br>
        </div>

    </div>
{% endblock %}

{% block js_app %}
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.bootstrap.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/buttons.bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/jszip.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/pdfmake.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/vfs_fonts.js' %}"></script>
    <script src="{% static 'plugins/datatables/buttons.html5.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/buttons.print.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.keyTable.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/responsive.bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.scroller.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/buttons.colVis.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.select.min.js' %}"></script>
    <script src="{% static 'static_turno/paciente/js/datatables.init.js' %}"></script>
    <script>
        window.onload = function () {
            document.getElementById("panel-table").style["opacity"] = "1";
        }
    </script>

    <script>
        function ajaxTraerTexto(numero) {
            $.ajax({
                url: "{% url 'informe:ajaxTraerTexto' %}",
                data: {
                    'numero': numero,
                },
                success: function (data) {
                    CKEDITOR.instances.id_texto.insertHtml(data['texto']);
                }

            })
        }
    </script>

{% endblock %}