core/urls.py
from django.conf.urls import url
from django.urls import include
from .views import Home, change_password
from django.contrib.auth.decorators import login_required

app_name = 'core'

urlpatterns = [
    url(r'^$', login_required(Home.as_view()), name='home'),
    url(r'', include('django.contrib.auth.urls')),
    url(r'^password/$', change_password, name='change_password'),
]

tecnico/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views
from .views import imprimir_fichatecnica, EstudioCorregir, marcar_estudio_corregido, detalle_insumos_imprimir, \
    remito_entrega_insumos_pdf, cerrar_estudio_con_informe, proveedor_listar, proveedor_buscar, insumo_listar, \
    lote_listar, lote_buscar, insumo_servicio_listado, remito_ingreso_proveedor_detalle, detalle_insumos_serv_imprimir, \
    remito_entrega_serv_insumos_pdf, listado_estudios_corregir, listado_insumos_gral_pdf, listado_lotes_pdf

app_name = 'tecnico'

urlpatterns = [
    url(r'insumo/$', views.index_insumos, name='index_insumo'),
    url(r'insumo/crear/$', login_required(views.InsumoCreate.as_view()), name='insumo_crear'),
    url(r'insumo/mod/(?P<pk>\d+)/$', login_required(views.InsumoUpdate.as_view()), name='insumo_mod'),
    url(r'insumo/tecins/$', views.index_tecxins, name='index_tecxins'),
    url(r'insumo/tecinsajuste/$', views.index_tecxins, name='index_tecxins_ajuste'),
    url(r'insumo/tecins/crear/$', views.tec_ins_crear, name='tec_ins_crear'),
    url(r'insumo/tecins/mod/(?P<pk_ti>\d+)/$', views.tec_ins_mod, name='tec_ins_mod'),
    url(r'insumo/tecins/eli/(?P<pk_ti>\d+)/$', views.tec_ins_eli, name='tec_ins_eli'),
    url(r'insumo/tecins/detalle$', views.insumo_tecnico_detalle, name='tec_ins_detalle'),
    url(r'insumo/tecins/entregar$', views.entregar_insumo, name='tec_ins_entregar'),
    url(r'insumo/tecins/ajustar$', views.ajustar_insumo, name='tec_ins_ajustar'),

    url(r'insumo/servicio/entregar$', views.entregar_insumo_servicio, name='servicio_ins_entregar'),
    url(r'insumo/servicio/ajustar$', views.ajustar_insumo_servicio, name='servicio_ins_ajustar'),

    url(r'protocolo/insxpro/$', views.IngresarInsumo, name='ingresar_insumo'),
    url(r'listadoRemitosIngreso/$', views.listado_remito_ingreso, name='listado_remito_ingreso'),
    url(r'listadoRemitoEgreso/$', views.listado_remito_egreso, name='listado_remito_egreso'),
    url(r'insumoMovimientosReporte/$', views.reporte_insumo_movimientos_farmacia, name='insumo_movimientos_reporte'),
    url(r'insumoMovimientos/$', views.insumo_movimientos_farmacia, name='insumo_movimientos_farmacia'),
    url(r'remitoingresonuevo/$', views.remito_ingreso_nuevo, name='remito_ingreso_nuevo'),
    url(r'insumoservicio/', insumo_servicio_listado, name='insumo_servicio'),
    url(r'insumoservicioajuste/', insumo_servicio_listado, name='insumo_servicio_ajuste'),

    url(r'^insumolistar/', insumo_listar, name='insumo_listar'),
    url(r'^insumolotelistar/', lote_listar, name='insumo_lote_listar'),
    url(r'^lotebuscarid/', lote_buscar, name='insumo_lote_buscar'),
    url(r'^insumoslistadogralimprimir/', listado_insumos_gral_pdf, name='insumo_listadogral_imprimir'),
    url(r'^insumosloteimprimir/', listado_lotes_pdf, name='insumo_lotes_imprimir'),
    url(r'^proveedorlistar/', proveedor_listar, name='proveedor_listar'),
    url(r'^proveedorbuscarcodigo/', proveedor_buscar, name='proveedor_buscar'),
    url(r'listadoestudiossolicitados/(?P<serviciocod>\d+)/$', views.listado_estudiossolicitados,
        name='listado_estudiossolicitados'),
    url(r'protocoloalta/(?P<pk>\d+)/$', login_required(views.ProtocoloAlta.as_view()), name='protocolo_alta'),
    url(r'protocolo/imprimirficha$', views.solicitar_imprimirficha, name='imprimir_ficha' ),
    url(r'^inf_tec/', imprimir_fichatecnica, name='informe_tecnico'),
    url(r'^tecnicoestudioscorregir/', listado_estudios_corregir, name='listado_estudios_corregir'),
    url(r'protocoloCambiarEstado$', views.protocolo_cambiar_estado, name='protocolo_cambiar_estado'),
    url(r'ajustenumeracion$', views.protocolo_ajuste_numeracion, name='protocolo_ajuste_numeracion'),
    url(r'ajusteagregarcodigo', views.protocolo_ajuste_agregar_codigo, name='protocolo_ajuste_agregar_codigo'),
    url(r'ajusteremovercodigo', views.protocolo_ajuste_remover_codigo, name='protocolo_ajuste_remover_codigo'),
    url(r'ajustenumeracionservicio$', views.protocolo_ajuste_numeracion_servicio,
        name='protocolo_ajuste_numeracion_servicio'),
    url(r'^estudiocorregir/', login_required(EstudioCorregir.as_view()), name='est_corregir'),
    url(r'^estudiomarcarcorregido/', marcar_estudio_corregido, name='est_marcar_corregido'),
    url(r'^detalleimprimir/', detalle_insumos_imprimir, name='detalle_insumos_imprimir'),
    url(r'^detalleimprimirservicio/', detalle_insumos_serv_imprimir, name='detalle_insumos_serv_imprimir'),
    url(r'^remitoprovisionimprimir/', remito_entrega_insumos_pdf, name='remito_entrega_insumos'),
    url(r'^remitoprovisionimprimirservicio/', remito_entrega_serv_insumos_pdf, name='remito_entrega_insumos_serv'),
    url(r'insumo/servicio/detalle$', views.insumo_servicio_detalle, name='servicio_ins_detalle'),
    url(r'^estudiocerrarinforme/', cerrar_estudio_con_informe, name='estudio_cerrar'),
    url(r'^detalleremitoproveedorimprimir/', remito_ingreso_proveedor_detalle, name='remito_ingreso_proveedor_detalle'),

    url(r'insumoMovimientosReporteIngresosExcel/$', views.reporte_farmacia_ingresos_excel, name='insumo_movimientos_reporte_ingresos_excel'),
    url(r'insumoMovimientosReporteEgresosExcel/$', views.reporte_farmacia_egresos_excel, name='insumo_movimientos_reporte_egresos_excel'),

]

tecnico/views.py
import datetime
import io
import json
from lib2to3.pgen2.pgen import DFAState

import pytz
import xlsxwriter
from PIL import Image
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from dateutil.relativedelta import relativedelta
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Q, Sum
from django.http import FileResponse
from django.http import HttpResponse, JsonResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_RIGHT, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm, inch
from reportlab.pdfgen import canvas
from reportlab.platypus import Table, Paragraph, TableStyle, Image, BaseDocTemplate, Frame, PageTemplate

from informe.views import get_codigos_linksimages_obs
from informe.views import websocket_actualizarinforme
from turno.models import *
from usuario.models import UserProfile
from .forms import *
from .models import TecnicoInsumo, InsumoDetalle, RemitoIngreso, Proveedor, InsumoRemitoIngreso, RemitoEntregaTecnico, \
    InsumoRemitoEntrega
from utils.protocolo_functions import get_protocolo_estado
from .utils.protocolo import update_protocolo_servicio, get_turno_protocolo_prefix, get_current_protocolo_count, \
    update_protocolo_servicio_current_count, check_valid_turno_date_protocolo

styles = getSampleStyleSheet()
styleN = styles['Normal']
styleH = styles['Heading1']
styleH5 = styles['Heading5']
styleH3 = styles['Heading3']


class NeverCacheMixin(object):
    @method_decorator(never_cache)
    def dispatch(self, *args, **kwargs):
        return super(NeverCacheMixin, self).dispatch(*args, **kwargs)


@login_required
def index_insumos(request):
    insumos = Insumo.objects.order_by('grupo', 'codigo')
    return render(request, 'insumo/abm_insumos.html', {'insumos': insumos})


insumo_fields_form = (
    'nombre', 'codigo', 'abreviatura', 'descripcion', 'grupo', 'unidad', 'unidad_tipo', 'habilitado', 'marca')


class InsumoCreate(CreateView):
    model = Insumo
    fields = insumo_fields_form
    template_name = 'insumo/insumo_form.html'
    success_url = reverse_lazy('tecnico:index_insumo')


class InsumoUpdate(UpdateView):
    model = Insumo
    fields = insumo_fields_form
    template_name = 'insumo/insumo_form.html'
    success_url = reverse_lazy('tecnico:index_insumo')


class InsumoDelete(DeleteView):
    model = Insumo
    template_name = 'insumo/insumo_confirm_delete.html'
    success_url = reverse_lazy('tecnico:index_insumo')


@login_required
def index_tecxins(request):
    context = {}
    tecnico_id = request.GET.get("tecnicoid", "")
    ajuste = request.GET.get("ajuste", "0")

    usuarios_tecnico_profile = UserProfile.objects.filter(perfil__contains='Tecnico', registra_stock=True)
    usuarios_tecnico = [userprofile.user for userprofile in usuarios_tecnico_profile]

    if tecnico_id != "" and tecnico_id != '1':
        tecnico = User.objects.get(id=tecnico_id)
        if tecnico:
            insumo_tecnico = TecnicoInsumo.objects.filter(tecnico=tecnico, insumo__grupo="3")
            context['tecnico_selected'] = tecnico

        else:
            insumo_tecnico = TecnicoInsumo.objects.filter(tecnico__in=usuarios_tecnico,
                                                          insumo__grupo="3").order_by('tecnico__last_name',
                                                                                      'tecnico__first_name')
    else:
        insumo_tecnico = TecnicoInsumo.objects.filter(tecnico__in=usuarios_tecnico, insumo__grupo="3").order_by(
            'tecnico__last_name', 'tecnico__first_name')

    list_tecnicos = {}
    profiles_tecnico = UserProfile.objects.filter(Q(perfil='Tecnico') | Q(perfil='Tecnico Recepcion'),
                                                  registra_stock=True).exclude(user__username='tecnico').order_by('user__last_name', 'user__first_name')
    for pt in profiles_tecnico:
        list_tecnicos[pt.user.id] = (pt.matricula, pt.user.last_name + ' ' + pt.user.first_name)

    insumos = Insumo.objects.filter(seregistrastock_tecnico=True).order_by('nombre')

    context['tecnicos'] = list_tecnicos
    context['insumo_tecnico'] = insumo_tecnico
    context['insumos'] = insumos

    template = 'insumo/index_tecxins.html'
    if ajuste == '1':
        template = 'insumo/index_tecxins_ajuste.html'

    return render(request, template, context)


@login_required
def insumo_tecnico_detalle(request):
    context = {}
    tecnico_id = request.GET.get("tecnicoid", "")
    insumo_id = request.GET.get("insumoid", "")

    if tecnico_id != "" and insumo_id != "":
        tecnico = User.objects.get(id=tecnico_id)
        insumo = Insumo.objects.get(id=insumo_id)
        insumo_tecnico = TecnicoInsumo.objects.filter(tecnico=tecnico, insumo=insumo).first()
        detalle_stock = InsumoDetalle.objects.filter(tecnico_insumo=insumo_tecnico).order_by('-fechahora')
        context = {"detalle_stock": detalle_stock, "insumo": insumo, "tecnico": tecnico,
                   "insumo_detalle_id": insumo_tecnico.id}

    return render(request, 'insumo/insumo_tecnico_detalle.html', context)


@login_required
@transaction.atomic
def tec_ins_crear(request):
    tecnicos = User.objects.all()
    insumos = Insumo.objects.filter(stock_almacen__gte=0)
    tecins = TecnicoInsumo.objects.all()
    if request.method == "POST":
        id_tec = request.POST['sele_tec']
        id_ins = {x: y for x, y in request.POST.items() if x.startswith('ins_')}
        tec = User.objects.get(pk=id_tec)
        ids = []
        for key in id_ins.keys():
            ids = key.replace("ins_", "")
        ins = Insumo.objects.filter(id__in=ids)
        for i in ins:
            tins = TecnicoInsumo(
                tecnico=tec,
                insumo=i,
                stock=request.POST['cant_ins_' + str(i.id)]
            )
            Insumo.objects.filter(id=i.id).update(
                stock_almacen=i.stock_almacen - int(request.POST['cant_ins_' + str(i.id)])
            )
            tins.save()
        return HttpResponseRedirect(reverse('tecnico:index_tecxins'))
    else:
        return render(request, 'insumo/tecxins_ingresar.html',
                      {"tecnicos": tecnicos, "insumos": insumos, "tecins": tecins})


@login_required
@transaction.atomic
def tec_ins_mod(request, pk_ti):
    tecins = TecnicoInsumo.objects.get(pk=pk_ti)
    tecnico = User.objects.get(pk=tecins.tecnico_id)
    ins = Insumo.objects.get(pk=tecins.insumo_id)
    max_stock = ins.stock_almacen + tecins.stock
    if request.method == "POST":
        nuevo_valor = int(request.POST["nuevo_stock"])
        if nuevo_valor > tecins.stock:
            Insumo.objects.filter(id=tecins.insumo_id).update(
                stock_almacen=ins.stock_almacen - (nuevo_valor - tecins.stock)
            )
        elif nuevo_valor < tecins.stock:
            Insumo.objects.filter(id=tecins.insumo_id).update(
                stock_almacen=ins.stock_almacen + (tecins.stock - nuevo_valor)
            )
        TecnicoInsumo.objects.filter(id=pk_ti).update(stock=nuevo_valor)
        return HttpResponseRedirect(reverse('tecnico:index_tecxins'))
    else:
        return render(request, 'insumo/tecxins_mod.html',
                      {"tecnico": tecnico, "tecins": tecins, "max": max_stock})


@login_required
@transaction.atomic
def IngresarInsumo(request):
    insumos = Insumo.objects.all()
    return render(request, 'protocolo/insumos.html', {'insumosxtecnico': insumos})


@login_required
@transaction.atomic
def tec_ins_eli(request, pk_ti):
    tecins = TecnicoInsumo.objects.get(pk=pk_ti)
    tecnico = User.objects.get(pk=tecins.tecnico_id)
    ins = Insumo.objects.get(pk=tecins.insumo_id)
    cantidad = tecins.stock
    if request.method == "POST":
        Insumo.objects.filter(id=tecins.insumo_id).update(
            stock_almacen=ins.stock_almacen + cantidad
        )
        TecnicoInsumo.objects.filter(id=pk_ti).delete()
        return HttpResponseRedirect(reverse('tecnico:index_tecxins'))
    else:
        return render(request, 'insumo/tecxins_eli.html',
                      {"tecnico": tecnico, "insumo": ins, "cantidad": cantidad})


@login_required
def listado_remito_ingreso(request):
    remitos_ingreso = RemitoIngreso.objects.all().order_by('-fecha')
    insumos = Insumo.objects.all()
    servicios = Servicio.objects.all().exclude(is_servicio_externo=True)
    tecnicos = UserProfile.objects.filter(perfil__contains='Tecnico').order_by('user__last_name', 'user__first_name')

    return render(request, 'insumo_remito/remitos_ingreso_listado.html',
                  {'remitos': remitos_ingreso, "insumos": insumos, "servicios": servicios, "tecnicos": tecnicos})


@login_required
def listado_remito_egreso(request):
    remitos_egreso_tecnico = RemitoEntregaTecnico.objects.all().order_by('-fecha')
    remitos_egreso_servicio = RemitoEntregaServicio.objects.all().order_by('-fecha')
    context = {'remitos_egreso_tecnico': remitos_egreso_tecnico, "remitos_egreso_servicio": remitos_egreso_servicio}
    return render(request, 'insumo_remito/remitos_egreso_listado.html', context)


@login_required
@transaction.atomic
def remito_ingreso_nuevo(request):
    response = {'success': False}

tecnico/templates/insumo_movimientos/Insumo_detalle_movimientos.html
{% extends "base.html" %}
{% load static %}

{% block css_app %}
    <link rel="stylesheet" href="{% static 'plugins/datatables-actualizado/DataTables-1.10.20/css/dataTables.bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-actualizado/Responsive-2.2.3/css/responsive.foundation.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-actualizado/Select-1.3.1/css/select.bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-actualizado/Buttons-1.6.1/css/buttons.dataTables.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/daterangepicker/daterangepicker.css' %}">
{% endblock %}

{% block content %}
    <div class="box" style="padding: 10px; margin-bottom: 25px">
            <h3 class="text-center text-blue margin-bottom">
            <strong style="padding-left: 15px">INSUMO - REPORTE DE MOVIMIENTOS</strong>
            </h3>
        <div class="margin-bottom">
            <h4 class="text-navy margin-bottom">1. Reporte: Detalle de Movimientos Insumo por Periodo</h4>
            <div class="row">
                <div class="col-sm-8">
                        <div class="col-xs-4" style="padding:0 ">
                            <label>Buscar Insumo</label>
                            <input onchange="cambiarinsumo_input(this.value,1)"
                                   class="form-control input-sm insumo-codigo"
                                   value=""
                                   id="insumo-1"
                                   name="insumo-1"
                                   placeholder="Buscar por Código o Nombre de Insumo"
                                   required>
                        </div>
                        <div class="col-xs-8" style="padding:0 ">
                            <label>Insumo Seleccionado</label>
                            <select class="form-control input-sm" onchange="cambiarinsumo_select(this.value,1)" id="select-insumos-1">
                                <option value="1" selected="selected" disabled>---</option>
                                {% for ins in insumos %}
                                    <option value="{{ ins.codigo }}" data-pres="{{ ins.unidad_tipo }}">{{ ins.nombre }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label>Seleccionar Periodo:</label>
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" class="form-control pull-right" id="date-range"/>
                        </div>
                    </div>
                </div>
            </div>
            <a class="btn btn-success" onclick="generar_reporte_1()"><i class="fas fa-file-pdf"></i> </span> <strong>Generar Reporte de Mov. </strong></a>
        </div>
        <div class="margin-bottom">
            <h4 class="text-navy margin-bottom">2. Reporte: Farmacia Ingresos por Periodo</h4>
            <div class="row">
                <div class="col-sm-4">
                    <div class="form-group">
                        <label>Seleccionar Periodo:</label>
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" class="form-control pull-right" id="date-range-2"/>
                        </div>
                    </div>
                </div>
            </div>
            <a class="btn btn-success" onclick="generar_reporte_2()"><i class="fas fa-file-excel"></i> </span> <strong>Generar Reporte Ingresos</strong></a>
        </div>
        <div class="margin-bottom">
            <h4 class="text-navy margin-bottom">3. Reporte: Farmacia Egresos por Periodo</h4>
            <div class="row">
                <div class="col-sm-4">
                    <div class="form-group">
                        <label>Seleccionar Periodo:</label>
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" class="form-control pull-right" id="date-range-3"/>
                        </div>
                    </div>
                </div>
            </div>
            <a class="btn btn-success" onclick="generar_reporte_3()"><i class="fas fa-file-excel"></i> </span> <strong>Generar Reporte Egresos</strong></a>
        </div>
    </div>
{% endblock %}

{% block js_app %}
    <script src="{% static 'plugins/datatables-actualizado/DataTables-1.10.20/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-actualizado/DataTables-1.10.20/js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-actualizado/Responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-actualizado/Responsive-2.2.3/js/responsive.bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-actualizado/Select-1.3.1/js/dataTables.select.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-actualizado/Buttons-1.6.1/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-actualizado/Buttons-1.6.1/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-actualizado/pdfmake-0.1.36/pdfmake.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-actualizado/pdfmake-0.1.36/vfs_fonts.js' %}"></script>
    <script src="{% static 'plugins/datatables-actualizado/JSZip-2.5.0/jszip.min.js' %}"></script>
    <script src="{% static 'bower_components/daterangepicker/daterangepicker.js' %}"></script>
    <script src="{% static 'plugins/input-mask/jquery.inputmask.js' %}"></script>
    <script src="{% static 'plugins/input-mask/jquery.inputmask.date.extensions.js' %}"></script>
    <script src="{% static 'plugins/input-mask/jquery.inputmask.extensions.js' %}"></script>

    <script>
        $('#date-range, #date-range-2').inputmask("d/m/y - d/m/y", { 'placeholder': 'dd/mm/yyyy - dd/mm/yyyy' });
        var datepick_range = $('#date-range').daterangepicker({
            opens: 'left',
            linkedCalendars: false,
            showDropdowns: true,
            autoApply: true,
            locale: {
                "format": "DD/MM/YYYY",
                "separator": " - ",
                "applyLabel": "Confirmar Fechas",
                "cancelLabel": "Cancelar",
                "fromLabel": "Desde",
                "toLabel": "a",
                "customRangeLabel": "Custom",

                "daysOfWeek": [
                    "Do",
                    "Lu",
                    "Ma",
                    "Mi",
                    "Ju",
                    "Vi",
                    "Sa"
                ],
                "monthNames": [
                    "Enero",
                    "Febrero",
                    "Marzo",
                    "Abril",
                    "Mayo",
                    "Junio",
                    "Julio",
                    "Agosto",
                    "Septiembre",
                    "Octubre",
                    "Noviembre",
                    "Diciembre"
                ],
                "firstDay": 1
            }})
        var datepick_range_2 = $('#date-range-2').daterangepicker({
            opens: 'left',
            linkedCalendars: false,
            showDropdowns: true,
            autoApply: true,
            locale: {
                "format": "DD/MM/YYYY",
                "separator": " - ",
                "applyLabel": "Confirmar Fechas",
                "cancelLabel": "Cancelar",
                "fromLabel": "Desde",
                "toLabel": "a",
                "customRangeLabel": "Custom",

                "daysOfWeek": [
                    "Do",
                    "Lu",
                    "Ma",
                    "Mi",
                    "Ju",
                    "Vi",
                    "Sa"
                ],
                "monthNames": [
                    "Enero",
                    "Febrero",
                    "Marzo",
                    "Abril",
                    "Mayo",
                    "Junio",
                    "Julio",
                    "Agosto",
                    "Septiembre",
                    "Octubre",
                    "Noviembre",
                    "Diciembre"
                ],
                "firstDay": 1
            }})
        var datepick_range_3 = $('#date-range-3').daterangepicker({
            opens: 'left',
            linkedCalendars: false,
            showDropdowns: true,
            autoApply: true,
            locale: {
                "format": "DD/MM/YYYY",
                "separator": " - ",
                "applyLabel": "Confirmar Fechas",
                "cancelLabel": "Cancelar",
                "fromLabel": "Desde",
                "toLabel": "a",
                "customRangeLabel": "Custom",

                "daysOfWeek": [
                    "Do",
                    "Lu",
                    "Ma",
                    "Mi",
                    "Ju",
                    "Vi",
                    "Sa"
                ],
                "monthNames": [
                    "Enero",
                    "Febrero",
                    "Marzo",
                    "Abril",
                    "Mayo",
                    "Junio",
                    "Julio",
                    "Agosto",
                    "Septiembre",
                    "Octubre",
                    "Noviembre",
                    "Diciembre"
                ],
                "firstDay": 1
            }})

        $("#insumo-1").autocomplete({
                source: "{% url 'tecnico:insumo_listar' %}",
                maxShowItems: 15,
                autoFocus: true,
                delay: 0,
        });
        function cambiarinsumo_select(insumoCodigo, nroOrden) {
            $('#insumo-'+nroOrden).val(insumoCodigo)
            $('#insumo-presentacion-'+nroOrden).val($('#select-insumos-'+nroOrden).find(':selected').data('pres'))
        }
        function cambiarinsumo_input(insumoCodigo, nroOrden) {
            $('#select-insumos-'+nroOrden).val(insumoCodigo)
            $('#insumo-presentacion-'+nroOrden).val($('#select-insumos-'+nroOrden).find(':selected').data('pres'))
        }


        function generar_reporte_1() {
            let insumo_codigo = $('#insumo-1').val()
            if (insumo_codigo !== ''){
                let startdate = datepick_range.data('daterangepicker').startDate;
                startdate = startdate.format('DD-MM-YYYY')
                let enddate = datepick_range.data('daterangepicker').endDate;
                enddate = enddate.format('DD-MM-YYYY')
                const url = '{% url 'tecnico:insumo_movimientos_reporte' %}?insumoCodigo=' + insumo_codigo  + '&fechaini=' +startdate + '&fechafin=' + enddate
                window.open(url, '_blank');
            }

        }
        function generar_reporte_2() {
            let startdate = datepick_range_2.data('daterangepicker').startDate;
            startdate = startdate.format('DD-MM-YYYY')
            let enddate = datepick_range_2.data('daterangepicker').endDate;
            enddate = enddate.format('DD-MM-YYYY')
            const url = '{% url 'tecnico:insumo_movimientos_reporte_ingresos_excel' %}?fechaini=' +startdate + '&fechafin=' + enddate
            window.open(url, '_blank');
        }
        function generar_reporte_3() {
            let startdate = datepick_range_3.data('daterangepicker').startDate;
            startdate = startdate.format('DD-MM-YYYY')
            let enddate = datepick_range_3.data('daterangepicker').endDate;
            enddate = enddate.format('DD-MM-YYYY')
            const url = '{% url 'tecnico:insumo_movimientos_reporte_egresos_excel' %}?fechaini=' +startdate + '&fechafin=' + enddate
            window.open(url, '_blank');
        }
    </script>
{% endblock %}